name: Deploy smart contracts

on:
  workflow_dispatch:
    inputs:
      DEPLOY_NETWORK:
        description: Network to deploy to
        required: true
        type: choice
        options:
        - mumbai_dev
        - matic_prod
        - eth_prod
      TOKEN_NAME:
        description: NFT contract name
        required: true
        default: Test NFT
      TOKEN_SYMBOL:
        description: NFT contract symbol
        required: true
        default: TNFT
      MAX_SUPPLY:
        description: Maximum supply (-1 for unlimited)
        required: false
        default: -1
      MINT_COMMISSION:
        description: Fee charged for minting
        required: false
        default: 0

env:
  POLYGONSCAN_KEY: ${{secrets.POLYGONSCAN_KEY}}
  PRIVATE_KEY_DEV: ${{secrets.PRIVATE_KEY_DEV}}
  PRIVATE_KEY_PROD: ${{secrets.PRIVATE_KEY_PROD}}
  ALCHEMY_URL: ${{secrets.ALCHEMY_URL}}

jobs:
  deploy:
    # if: contains('[ $repo_owner , "username1", "username2"...]', github.actor)
    if: contains('[ ${{github.repository_owner}} ]', github.actor)
    runs-on: ubuntu-latest
    env:
      TOKEN_NAME: ${{ github.event.inputs.TOKEN_NAME }}
      TOKEN_SYMBOL: ${{ github.event.inputs.TOKEN_SYMBOL }}
      MAX_SUPPLY: ${{ github.event.inputs.MAX_SUPPLY }}
      MINT_COMMISSION: ${{ github.event.inputs.MINT_COMMISSION }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npx hardhat compile
      - run: npx hardhat deploy --network ${{ github.event.inputs.DEPLOY_NETWORK }}
  