name: Deploy to Polygon mainnet

on:
  workflow_dispatch:
    inputs:
      TOKEN_NAME:
        description: NFT contract name (default "Dynamic NFT")
        required: false
      TOKEN_SYMBOL:
        description: NFT contract symbol (default "DNFT")
        required: false
      MAX_SUPPLY:
        description: Maximum supply allowed (default -1, i.e. unlimited)
        required: false
      MINT_COMMISSION:
        description: Fee received for minting (default 1)
        required: false

env:
  POLYGONSCAN_KEY: ${{secrets.POLYGONSCAN_KEY}}
  PRIVATE_KEY_DEV: ${{secrets.PRIVATE_KEY_DEV}}
  PRIVATE_KEY_PROD: ${{secrets.PRIVATE_KEY_PROD}}
  ALCHEMY_URL: ${{secrets.ALCHEMY_URL}}
  repo_owner: ${{github.repository_owner}}

jobs:
  deploy_to_polygon:
    # if: contains('[ $repo_owner , "username1", "username2"...]', github.actor)
    if: contains('[ $repo_owner ]', github.actor)
    runs-on: ubuntu-latest
    env:
      TOKEN_NAME: ${{ github.event.inputs.TOKEN_NAME }}
      TOKEN_SYMBOL: ${{ github.event.inputs.TOKEN_SYMBOL }}
      MAX_SUPPLY: ${{ github.event.inputs.MAX_SUPPLY }}
      MINT_COMMISSION: ${{ github.event.inputs.MINT_COMMISSION }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npx hardhat compile
      - run: npx hardhat deploy --network matic_prod
  